DATABASE_LOCATION = "assets/duckair.db"
CERTIFICATE_KEY = "assets/duckair.key"
CERTIFICATE = "assets/duckair.crt"
LOG_LEVEL = "info"
# SQLLite
DATABASE_LOCATION = "assets/duckair.db"
# Postgres
DATABASE_URL='postgres://phil:test!@localhost/flight_plan'

